name: Update apt
apt: update_cache=yes


name: Install dependencies
apt: name=[gnupg, wget] state=present


name: Add MongoDB repo key
apt_key:
url: https://www.mongodb.org/static/pgp/server-6.0.asc
state: present


name: Add MongoDB repo
apt_repository:
repo: "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse"
state: present


name: Install MongoDB
apt: name=mongodb-org state=present update_cache=yes


name: Ensure mongod is enabled and started
service: name=mongod state=started enabled=yes


name: Wait for mongod to be ready
wait_for: host=127.0.0.1 port=27017 timeout=30


name: Create admin user
shell: |
mongo --eval "db.getSiblingDB('admin').createUser({user